### ISSUE TITLE
Which License belongs this work to?

### ISSUE THREAD

**Issue by brummer10** [SoundDevelopment/3D_knob_lnf#1]
Hi
I like to use parts of your code to draw the knobs in my application, which is under the GPL v3. I looked for a license file in your repository but only found 

`Copyright: Marcel Huibers (c) 2022 All Rights Reserved`

So I like to know if you are fine with, when I grab out some code of your work and use it?

regards
hermann

**Comment by SoundDevelopment** [comment]
Ah, yes. No worries. Thought I had already included that.
It's all MIT, so absolutely fine to grab it and adapt it.

**Comment by brummer10** [comment]
Many thanks. They look really great!
